version: "3"

services:
  master:
    image: hadoop-hive-spark-master
    hostname: master
    depends_on:
      - metastore
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9870 || exit 1" ]
    environment:
      SPARK_MASTER_HOST: 172.28.1.1
      SPARK_LOCAL_IP: 172.28.1.1
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
      - "4043:4043"
      - "8080:8080"
      - "8088:8088"
      - "8888:8888"
      - "9000:9000"
      - "9868:9868"
      - "9870:9870"
      - "10000:10000"
      - "18080:18080"
      - "19888:19888"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - namesecondary:/opt/hadoop/dfs/namesecondary
      - ./notebook:/notebook
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "metastore:172.28.1.4"

  worker1:
    image: hadoop-hive-spark-worker
    hostname: worker1
    depends_on:
      - master
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9864 || exit 1" ]
    environment:
      SPARK_MASTER_HOST: 172.28.1.1
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: worker1
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "master:172.28.1.1"
      - "worker2:172.28.1.3"
      - "metastore:172.28.1.4"

  worker2:
    image: hadoop-hive-spark-worker
    hostname: worker2
    depends_on:
      - master
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9864 || exit 1" ]
    environment:
      SPARK_MASTER_HOST: 172.28.1.1
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker2
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    ports:
      - "8043:8042"
      - "8082:8082"
      - "9865:9864"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "metastore:172.28.1.4"

  metastore:
    image: postgres:11
    hostname: metastore
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16